### ISSUE TITLE
Question: What crypto can the app mine?

### ISSUE THREAD

**Issue by spogulis** [devinbileck/IdleMiner#2]
Like the title says.. Which cryptocurrency is this app for? Also, where is the mined amount stored? Does the app give private keys to the wallet? Is there a "transfer from wallet" function within the GUI?

**Comment by devinbileck** [comment]
This application is not itself a mining application, it simply launches the xmr-stak mining application while your computer is idle. So you can mine whatever currencies as supported by [xmr-stak](https://github.com/fireice-uk/xmr-stak).
